### ISSUE TITLE
Tiles don't behave when loading project?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#121]
I can't quite describe this accurately, so I'd appreciate if someone could try to recreate:

1. New project
2. Add server layers via plugin
3. Save project
4. Close project
5. Reopen project

What those steps give me (I think) is a reduced extent at a given scale, which doesn't load tiles on zoom/pan.

**Comment by mnboos** [comment]
That's expected behavior. If you close the project, the vector tiles reader will disconnect from the source. It won't automatically reconnect when a project is opened.

**Comment by tomchadwin** [comment]
I don't think it's the behaviour a user expects - I certainly don't. A project should be the same when you open it as when you saved it. The behaviour should be the same as a project with a saved tiled raster layer.

**Comment by mnboos** [comment]
With 'expected behavior' I meant it's not a bug but the current implementation. I think I will have to change the implementation. @sfkeller

**Comment by tomchadwin** [comment]
Ah, sure. Don't change behaviour just on the strength of my opinion, but if you or others agree, sure.

**Comment by sfkeller** [comment]
I agree with @tomchadwin and have the same expectation on any QGIS project: 
When a user saves the current project, then clicks on "New", all resources are released (as requested in #84). 
When the user re-opens the project all layers should be restored (i.e. reconnected) including raster/vector data sources, webservices - and VT.

**Comment by mnboos** [comment]
And if there are multiple vector tile reader sources in the project, each should be connected?

**Comment by sfkeller** [comment]
Exactly - similar to multiple WMS/WMTS. 

If that is not possible (due to complexity or resource constraints), the MVT plugin should prevent loading more than one vector tile reader source.

**Comment by mnboos** [comment]
Wanted to implemented this and realized, that layer custom properties won't be persisted?!

I can save the connection in another way, but the question, why layer custom properties aren't persisted, stays open.

**Comment by tomchadwin** [comment]
They are persisted - they are saved to the `.qgs` project file.

**Comment by mnboos** [comment]
But when I reload the same project, all values accessed via .customProperty(...) are None.

**Comment by tomchadwin** [comment]
After adding the VT layers, did you save your project before closing it?

**Comment by mnboos** [comment]
Yes. I'll have a look at the project file.

The key is empty. Probably a problem because I wanted to save a whole object, what then leads to invalid xml.

**Comment by tomchadwin** [comment]
Do you need to serialize the XML into a string? I was working on something completely different and saw HTML encoded HTML tags for a value, so the customProperty value could contain XML-style tags. I'll see if I can dig out the example.

**Comment by mnboos** [comment]
If solved it by saving the dict as string and creating a dict again when loading. Thanks anyway.

**Comment by tomchadwin** [comment]
Splendid. In case anyone needs it in the future, the example I found was in the grid setting:

```xml
<LineSymbol type="QString">&lt;symbol alpha="1" clip_to_extent="1" type="line" name="line symbol">
 &lt;layer pass="0" class="SimpleLine" locked="0">
  &lt;prop k="capstyle" v="square"/>
  &lt;prop k="customdash" v="5;2"/>
  &lt;prop k="customdash_map_unit_scale" v="0,0,0,0,0,0"/>
  &lt;prop k="customdash_unit" v="MM"/>
  &lt;prop k="draw_inside_polygon" v="0"/>
  &lt;prop k="joinstyle" v="bevel"/>
  &lt;prop k="line_color" v="0,0,0,255"/>
  &lt;prop k="line_style" v="solid"/>
  &lt;prop k="line_width" v="0.26"/>
  &lt;prop k="line_width_unit" v="MM"/>
  &lt;prop k="offset" v="0"/>
  &lt;prop k="offset_map_unit_scale" v="0,0,0,0,0,0"/>
  &lt;prop k="offset_unit" v="MM"/>
  &lt;prop k="use_custom_dash" v="0"/>
  &lt;prop k="width_map_unit_scale" v="0,0,0,0,0,0"/>
 &lt;/layer>
&lt;/symbol>
</LineSymbol>
```

Actually, looking that that properly, I can't really make sense of what it's doing. Never mind.

**Comment by mnboos** [comment]
Done

**Comment by tomchadwin** [comment]
Apologies for reviving this, but this still isn't working for me (Win7, QGIS 3.8.2, VTR 3.1.0.

1. Used VTR to connect to https://s3-eu-west-1.amazonaws.com/tiles.os.uk/data/vector/open-zoomstack/config.json (cicking Basemap defaults, and adding all layers)
2. Pan/zoom around a bit
3. Save and close project
4. Open project

New tiles don't seem to load, and this is logged:

```
Loading aborted as there are no layers of the current connection already loaded.
```

**Comment by tomchadwin** [comment]
Predictably, though, I've just failed to recreate this issue. It happens with a project I created yesterday, but not with one I created today.
