### ISSUE TITLE
QGIS 3 on Mac - no module named "future" & "past"

### ISSUE THREAD

**Issue by klokan** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#196]
QGIS3, clean install of the latest stable release from official (http://www.kyngchaos.com/software/qgis) binaries. Installation of the plugin fails with:

![screen shot 2018-04-16 at 10 52 09](https://user-images.githubusercontent.com/59284/38799253-3eba3182-4164-11e8-87cd-13a403b8b334.png)

Couldn't load plugin 'vector_tiles_reader' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/__init__.py", line 17, in classFactory
    from .vtr_plugin import VtrPlugin
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vtr_plugin.py", line 28, in 
    from .util.network_helper import url_exists, load_url
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/util/network_helper.py", line 1, in 
    from future import standard_library
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.0.0-Girona Girona, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by mnboos** [comment]
Thanks for the report. I removed all the future imports with commit 76a80da0a55b715cadd35a961e5c76fd72f58cf3 and hope the bug is fixed with this measure.

**Comment by mnboos** [comment]
@klokan  The version 2.0.1 has been released now.

**Comment by klokan** [comment]
Funny change. The plugin still does not install.

Now module "past" is not found:

```
Couldn't load plugin 'vector_tiles_reader' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'past' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/__init__.py", line 17, in classFactory
    from .vtr_plugin import VtrPlugin
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vtr_plugin.py", line 29, in 
    from .util.tile_helper import (
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/util/tile_helper.py", line 3, in 
    from .global_map_tiles import GlobalMercator
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/util/global_map_tiles.py", line 70, in 
    from past.utils import old_div
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'past'


Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.0.0-Girona Girona, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/klokan/Library/Application Support/QGIS/QGIS3/profiles/default/python
```

**Comment by mnboos** [comment]
Thanks again! Is fixed and will be included in the next release.

**Comment by mnboos** [comment]
The plugin version 2.0.2 is published and OSX should work fine now.

**Comment by sfkeller** [comment]
Resolved?

**Comment by mnboos** [comment]
@klokan Is the current version (2.0.3) working?

**Comment by danbjoseph** [comment]
similar error on my system. after looking at #258 and reading the [docs](https://pypi.org/project/past/) for the `past` module, i tried `pip3 install future` but got:
```
pip3 install future
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (0.17.1)
```
the error is as below. i'm noticing that the above file path has `3.7` and the error message says `Python version: 3.6.6` so `pip3` doesn't seem to be operating on the python being used by QGIS. i'm not sure how to install the module for the right python?
```
Couldn't load plugin 'go2mapillary' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'past' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/__init__.py", line 49, in classFactory
    from .mapillary_explorer import go2mapillary
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 54, in 
    from .mapillary_coverage import mapillary_coverage, LAYER_LEVELS
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_coverage.py", line 26, in 
    from go2mapillary.extlibs import mapbox_vector_tile
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs/mapbox_vector_tile/__init__.py", line 1, in 
    from . import encoder
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs/mapbox_vector_tile/encoder.py", line 3, in 
    from past.builtins import long
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'past'


Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 17:02:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.2.1-Bonn Bonn, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/danbjoseph/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
```

**Comment by danbjoseph** [comment]
i reinstalled python and QGIS and then
```
~ python3 --version
Python 3.6.8
~ pip3 install future
```
and the plugin seems to be working now

**Comment by mnboos** [comment]
Your error says

> Couldn't load plugin 'go2mapillary'

This repo is for the Vector Tiles Reader plugin. ;-)

**Comment by danbjoseph** [comment]
not enough ☕️ i guess.
sorry about that.

**Comment by mnboos** [comment]
No problem. One can never have enough ☕️
