### ISSUE TITLE
Add menu entry for load/reload

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#45]
"Reload/Load features overlapping the view extent"

**Comment by mnboos** [comment]
Done.

Notice, that "Reload" ignores the a tile limit, if any was set. This could be improved with a proper caching mechanism (see #26)

**Comment by sfkeller** [comment]
After loading a file source (e.g. with Name "Koh Samui") the Reload Button is set to "Reload (Koh Samui)".
When this layer is removed, the Reload Button still shows "Reload (Koh Samui)" and actually reloads this even when there is no such layer anymore.

**Comment by mnboos** [comment]
I don't see that as a bug. The reload button just reloads the area of the current QGIS extent from the last source used. This could even be used as debugging tool: Load area, pan, delete current layers, reload.

**Comment by sfkeller** [comment]
@mnboos : I see. But then, would'nt we need an "Unload" button a and check when the same area is loaded a second time?
This issue opens an interesting discussion about how vector tiles are handled, being somehow a hybrid with raster: It's obvious that raster tiles can be reloaded - but there you don't expect to analyse the whole "layer" as you would expect in a vector layer.

**Comment by mnboos** [comment]
@sfkeller Is it a problem, if the same area is loaded multiple times? Now with the caching implemented it's really fast if the same area is loaded multiple times and the layer sources (i.e. the GeoJSON files) will not be changed or modified.

**Comment by sfkeller** [comment]
Coming back to the fundamental discussion how vector tiles (VT) should be treated: I see two generic use cases, 1. as background 2. for inspection and analysis.

1. is raster alike, potentially worldwide, graphics is more important than analysis (no counting features etc.). The background (default) style (#52 ) and the mask layer (#57) are important and mask layer features need to be loaded. A VT source is one source consisting of a group of layers; that group is loaded once (no one loads two same background or base maps as two separate layers); reloading (and unloading) should be automated. 
1. is for analysis (counting features, measuring length/area, doing statistics and spatial operations) typically bound to a local perimeter area, all features merged. The mask layer (#57) is unimportant. That mode of VT source can be loaded several times with differing set of layers/tables - even from the same area.

Let us think about what that means in terms of options in the modal dialog (and behind the scenes)! Should we offer two "modes" a VT layer can have?

**Comment by tomchadwin** [comment]
For me, 1. is "add layer" and 2 is "import layer".

1 is the intended use-case for VT - the flexibility of vector styling and resolution-independence without a single massive download.

2 is really only of use to devs. 

This is why I still think some thought should be given to recreating the auto load and unload, as per raster tiles. What's the point of it being tiled otherwise? I'm also therefore not sure that feature merging is so crucial.

**Comment by sfkeller** [comment]
@tomchadwin Thanks for your important input. There's the fundamental discussion what VT's are (which you and me raised) and finally, what the purpose is of this plugin. Initially, I thought the plugin is for inspection only (i.e. for devs.) - now given the great implementation success thank's to @mnboos - we have a dilemma, and I hope the plugin can cover both "modes" 

P.S. Keep in mind though, that MB GL JS styles only can rendered with a JS lib. so no chance QGIS can do that - at least not within this release of VT Reader plugin.

**Comment by tomchadwin** [comment]
Re: your PS

Firstly, I guess with work the styles *could* be imported. The interest for me is style *export* from QGIS. These are all steps towards that.

Dare I say that even export geometry to VT might be a possibility?

**Comment by mnboos** [comment]
See Geometry export to mbtiles #63
