### ISSUE TITLE
MVT reader does not release all resources?

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#84]
Following work flow:
* Load MVT reader
* Create new project ("New" in toolbar)
* Change zoom
* => MVT reader still pops up an loads tiles.
* Clicking on "New" project once again, MVT reader possibly releases all ressources as expected.

**Comment by mnboos** [comment]
Fixed

**Comment by sfkeller** [comment]
QGIS 2.18.14 Win and plugin 1.2.5: Still the same issues: 
- Load QMT as raster background 
- Load a VT source, e.g. => Group "OpenMapTiles" appears in Layers Panel
- Remove group "OpenMapTiles"
- Zoom in/out => Group "OpenMapTiles" loads tiles and reappears (while it should have gone after "Remove")

**Comment by sfkeller** [comment]
Even when creating a "New" project, after having used a VT connection, the tile index display (lower left of window, see below) remains. That should be removed too IMHO.
![grafik](https://user-images.githubusercontent.com/43340/32864359-30ea5b58-ca5f-11e7-9fe5-60cfdc38bb36.png)

**Comment by mnboos** [comment]
Done
